version: '2.1'

networks:
  monitoring:
    driver: bridge
volumes:
    prometheus_data: {}
    grafana_data: {}
services:
  prometheus:
    image: prom/prometheus:v2.20.1
    container_name: prometheus
    volumes:
      - /home/rithuparnakd/projectData/phase2Training/Docker/data/prometheus/prometheus.yml:/etc/prometheus/config.yml
      # - prometheus_data:/prometheus
    command: '--config.file=/etc/prometheus/config.yml'
    ports:
      - 18080:8080

    networks:
      - monitoring
  grafana:
    image: grafana/grafana:7.1.5
    container_name: grafana
    volumes:
      - /home/rithuparnakd/projectData/phase2Training/Docker/data/grafana:/var/lib/grafana
      # - ./grafana/provisioning:/etc/grafana/provisioning
    user: '104'
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - 3001:3000

    networks:
      - monitoring